services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      PLATONUS_LOGIN_URL: https://platonus.tau-edu.kz/mail?type=1
      PLATONUS_BASE_URL: https://platonus.tau-edu.kz
      PLAYWRIGHT_TIMEOUT_MS: 60000
      PLAYWRIGHT_HEADLESS: "true"
